### ISSUE TITLE
(Request) F-Droid

### ISSUE THREAD

**Issue by tokenmath** [Ivy-Apps/ivy-wallet#2049] opened 2023-03-17 19:57 UTC
Since it is an open project, why not include it in the F-Droid app platform?

**Comment by ILIYANGERMANOV** [comment] 2023-08-31 22:48
I'm happy to do so! If someone can create a GitHub Action workflow to upload it to FDroid - let's do it!

**Comment by ILIYANGERMANOV** [comment] 2023-09-01 22:59
Duplicate of https://github.com/Ivy-Apps/ivy-wallet/issues/104

**Closed by ILIYANGERMANOV** 2023-09-01 22:59 UTC
Labels: important, help wanted, approved

**Comment by CodeCubeNeo** [comment] 2024-02-16 20:00
Any updates on this?

**Comment by ILIYANGERMANOV** [comment] 2024-02-16 21:04
#104 this is the open-ticket; no contributors want to work on it so far :/
