### ISSUE TITLE
End Date To Preplanned Payment

### ISSUE THREAD

**Issue by ivywallet** [Ivy-Apps/ivy-wallet#331] opened 2021-12-29 03:18 UTC
Preplanned payment is great!! But there should be an end date also to stop adding the recurring expense after a certain date.

**Comment by Pkcarreno** [comment] 2022-06-03 19:20
Duplicate of https://github.com/ILIYANGERMANOV/ivy-wallet/issues/143

**Closed** 2022-08-25 08:40 UTC
