### ISSUE TITLE
Upload Image Of Receipt 

### ISSUE THREAD

**Issue by ivywallet** [Ivy-Apps/ivy-wallet#1156] opened 2022-07-25 20:22 UTC

**Comment by code-a1** [comment] 2022-08-22 14:28
#1241 Duplicate

**Comment by Aditya137x** [comment] 2022-08-25 13:45
Duplicate of https://github.com/Ivy-Apps/ivy-wallet/issues/6

**Closed by Aditya137x** 2022-08-25 13:45 UTC
Labels: duplicate, feature, user request

**Comment by Hhiman** [comment] 2022-08-25 14:34
![Uploading Screenshot_20220824-200257.png…]()
