### ISSUE TITLE
[BUG] Time zones look to be ignored 

### ISSUE THREAD

**Issue by stetimi** [Ivy-Apps/ivy-wallet#3167] opened 2024-04-29 00:03 UTC
### Please confirm the following

- [X] I checked [the current issues](https://github.com/Ivy-Apps/ivy-wallet/issues) for duplicate problems

### Describe the bug

I'm in Hong Kong which is 8 hours ahead of UTC.
I entered a transfer at 7.30am on 29th April. It appeared in the main view listed with the 28th April transactions.

I had to delete the transfer and re enter after 8am, it then showed under 29th April.

### To Reproduce

Hopefully should be clear how to reproduce.

### App version

4.6.2

### Smartphone

Pixel 7 plus

**Comment by ivywallet** [comment] 2024-04-29 00:05
Thank you @stetimi for raising Issue #3167! 🚀
What's next? Read our **[Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md) 📚**.

_Tagging @ILIYANGERMANOV for review & approval 👀_

**Comment by ynshung** [comment] 2024-05-02 10:49
Related to #3033

**Comment by aleroza** [comment] 2024-05-05 12:25
Hello. It looks like one of the "manifestations" of this bug.


https://github.com/Ivy-Apps/ivy-wallet/assets/48179175/451b394a-7f48-43e1-bce9-9e8acd9cb07e

**Comment by rishi2062** [comment] 2024-05-27 08:07
@ILIYANGERMANOV , maybe this issue is also a duplicate of Issue #3145, #3212 ,

**Comment by rishi2062** [comment] 2024-06-01 20:44
I'm on it

**Comment by rishi2062** [comment] 2024-06-01 20:44
Let me try to avoid any time conversion at UI layer

**Comment by rishi2062** [comment] 2024-06-01 21:55
I'm on it

**Comment by ivywallet** [comment] 2024-06-01 21:57
Thank you for your interest @rishi2062! 🎉
Issue #3167 is assigned to you. You can work on it! ✅

_If you don't want to work on it now, please un-assign yourself so other contributors can take it._

Also, make sure to read our [Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md).

**Closed** 2024-06-02 00:07 UTC
Labels: bug, approved, P0
