### ISSUE TITLE
[BUG] Balance not updated

### ISSUE THREAD

**Issue by tthuyxx** [Ivy-Apps/ivy-wallet#3388] opened 2024-08-02 09:52 UTC
### Please confirm the following

- [X] I checked [the current issues](https://github.com/Ivy-Apps/ivy-wallet/issues) for duplicate problems

### Describe the bug

When i add income or expense my balance in the wallet dont automatically add up with the amount of money i currently have so i am a bit confuse. I hope this get fix soon

### To Reproduce

1. 

### Expected behavior

The balance should be add up automatically 

### App version

v2024.07.28-192

### Smartphone

Samsung Galaxy S20 FE Android 13

**Comment by ivywallet** [comment] 2024-08-02 09:55
Thank you @tthuyxx for raising Issue #3388! 🚀
What's next? Read our **[Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md) 📚**.

_Tagging @ILIYANGERMANOV for review & approval 👀_

**Comment by letsaguiar** [comment] 2024-08-03 05:52
I couldn't reproduce this behaviour on my machine.
https://streamable.com/ws81py

Running Android API 33 - Android 13

**Comment by tthuyxx** [comment] 2024-08-03 11:22
https://github.com/user-attachments/assets/47ac9410-e10b-4664-b010-d8c578fe466f

Ye but i still have that issue. As you can see my balance at first is 875.000 but when i added 200.000 it doesnt automatically added up so the bug is still there

**Comment by akashs056** [comment] 2024-08-03 12:36
> I couldn't reproduce this behaviour on my machine. https://streamable.com/ws81py
> 
> Running Android API 33 - Android 13

This issue is occurring on the debug APK, which is downloaded directly from the code. The Play Store version is working fine.

**Comment by akashs056** [comment] 2024-08-03 13:09
I'm on it

**Comment by ivywallet** [comment] 2024-08-03 13:11
Thank you for your interest @akashs056! 🎉
Issue #3388 is assigned to you. You can work on it! ✅

_If you don't want to work on it now, please un-assign yourself so other contributors can take it._

Also, make sure to read our [Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md).

**Comment by akashs056** [comment] 2024-08-04 07:49
@ILIYANGERMANOV 
I have tested the latest PR, and issues #3387 and #3388 have been resolved by this PR. Please make sure to close these issues. Thank you!   
Before : 

https://github.com/user-attachments/assets/42a04c5c-839b-4928-8b20-7df20225fe64

After : 

https://github.com/user-attachments/assets/e4e3822d-d07b-4bc8-ae8e-7666502a0170

**Comment by ILIYANGERMANOV** [comment] 2024-08-04 10:46
Should be fixed by https://github.com/Ivy-Apps/ivy-wallet/pull/3390

**Closed by ILIYANGERMANOV** 2024-08-04 10:46 UTC
Labels: bug, approved

**Comment by tthuyxx** [comment] 2024-08-04 16:03
I now knew where is the issue. For example when i add my income or expense the date of the app is set for tomorrow so it didn't appear right away but it will appear tomorrow. (I dont know why the app set it like that). But thank you for solving my issue. I appreciate it!

**Comment by tthuyxx** [comment] 2024-08-05 08:43
https://github.com/user-attachments/assets/992b1046-de84-418f-9aa1-08d3b9b13132

This is what i talked about earlier. As you can see when i add the money it didnt add up immediately and the day is still set at today 5/8/2024. But when i changed to 4/8/2024 then it will get added up into my wallet. I dont know if this is a bug or a feature or this is only happening to me? Can anyone help me fix this on my phone
