### ISSUE TITLE
Add Notifications To Planned Payments

### ISSUE THREAD

**Issue by ivywallet** [Ivy-Apps/ivy-wallet#232] opened 2021-12-09 23:48 UTC
To allow remind users to pay and not miss datelines.

**Comment by StarHamster** [comment] 2022-04-23 09:24
Depends on #76

**Comment by Aditya137x** [comment] 2022-08-24 11:10
Duplicate of https://github.com/Ivy-Apps/ivy-wallet/issues/76

**Closed** 2023-08-31 22:19 UTC
Labels: feature, user request, important
