### ISSUE TITLE
Ability to add Subcategories to Major Categories with few presets like Dinner, Breakfast, Lunch, Snacks etc  in Food (feature similar to Money Manager)

### ISSUE THREAD

**Issue by ivywallet** [Ivy-Apps/ivy-wallet#1649] opened 2022-12-28 19:22 UTC

**Comment by theRealPadster** [comment] 2023-01-23 03:31
Dupe of https://github.com/Ivy-Apps/ivy-wallet/issues/1747

**Closed** 2023-08-31 22:05 UTC
