### ISSUE TITLE
If we could add an image import format. We could add. Recipt pictures. Bill pictures etc.. That would help alott. Thanks.. Waiting for the response

### ISSUE THREAD

**Issue by ivywallet** [Ivy-Apps/ivy-wallet#939] opened 2022-05-24 03:25 UTC

**Comment by code-a1** [comment] 2022-08-22 14:27
#1241 Duplicate

**Comment by Aditya137x** [comment] 2022-08-25 13:46
Duplicate of https://github.com/Ivy-Apps/ivy-wallet/issues/6

**Closed by Aditya137x** 2022-08-25 13:46 UTC
Labels: duplicate, feature, user request
