### ISSUE TITLE
Please Add Credit Card Feature So That We Can Add Expenses To Credit Card Account And At A Particular Date Of Each Month That Months Due Will Be Remited From Associated Bank Account

### ISSUE THREAD

**Issue by ivywallet** [Ivy-Apps/ivy-wallet#1136] opened 2022-07-16 18:50 UTC

**Comment by Aditya137x** [comment] 2022-08-24 11:01
Duplicate of https://github.com/Ivy-Apps/ivy-wallet/issues/11

**Closed by Aditya137x** 2022-08-24 11:01 UTC
