### ISSUE TITLE
Sub Categories

### ISSUE THREAD

**Issue by ivywallet** [Ivy-Apps/ivy-wallet#1044] opened 2022-06-16 04:14 UTC
I have my own budget (in excel) grouped in "parent" categories example Insurances (as parent) with life, home, health, etc (as child) which the amount of each can be show as an one amount in parent.

**Comment by Aditya137x** [comment] 2022-08-25 08:24
Duplicate of https://github.com/Ivy-Apps/ivy-wallet/issues/7

**Closed by Aditya137x** 2022-08-25 08:24 UTC
