### ISSUE TITLE
Multiple Categories Per Expense

### ISSUE THREAD

**Issue by ivywallet** [Ivy-Apps/ivy-wallet#387] opened 2022-01-04 02:19 UTC
In order to keep all credit card transactions aggregated, it would be nice to have a category for credit card + a category for the expense
eg: credit card, food

**Comment by Aditya137x** [comment] 2022-08-25 08:10
Duplicate of https://github.com/Ivy-Apps/ivy-wallet/issues/7

**Closed by Aditya137x** 2022-08-25 08:10 UTC
