### ISSUE TITLE
[BUG] Date when adding an entry is 1 day in advance

### ISSUE THREAD

**Issue by nokmanok** [Ivy-Apps/ivy-wallet#3210] opened 2024-05-24 21:51 UTC
### Please confirm the following

- [X] I checked [the current issues](https://github.com/Ivy-Apps/ivy-wallet/issues) for duplicate problems

### Describe the bug

When I add an entry and put the date and time, the date will be offset by 1 day in advance

### App version

4.6.3 (163)

### Smartphone

Samsung Flip 5

**Comment by ivywallet** [comment] 2024-05-24 21:53
Thank you @davecordova13 for raising Issue #3210! 🚀
What's next? Read our **[Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md) 📚**.

_Tagging @ILIYANGERMANOV for review & approval 👀_

**Comment by ILIYANGERMANOV** [comment] 2024-05-25 15:29
Duplicate of #2876

**Comment by ILIYANGERMANOV** [comment] 2024-05-25 15:30
Duplicate of #3145

**Closed by ILIYANGERMANOV** 2024-05-25 15:29 UTC
Labels: bug
