### ISSUE TITLE
Planned Transfers 

### ISSUE THREAD

**Issue by ivywallet** [Ivy-Apps/ivy-wallet#1146] opened 2022-07-21 14:37 UTC
So if I have a transfer from my bank to my savings every Friday, there should be a planned Transfer to make it easier to set it weekly rather than creating individual Income wnd Expense.

**Comment by Aditya137x** [comment] 2022-08-25 13:40
Duplicate of https://github.com/Ivy-Apps/ivy-wallet/issues/173

**Closed by Aditya137x** 2022-08-25 13:40 UTC
