### ISSUE TITLE
Decimal number 

### ISSUE THREAD

**Issue by Muhmad-hamdi** [Ivy-Apps/ivy-wallet#3120] opened 2024-04-11 06:32 UTC
### Please confirm the following:

- [X] I've checked [the current issues](https://github.com/Ivy-Apps/ivy-wallet/issues) for duplicate issues.
- [X] I've requested a single (only one) feature/change in this issue. It complies with the One Request Per GitHub Issue (ORPGI) rule.
- [X] My issue is well-defined and describes how it should be implemented from UI/UX perspective.

### What do you want to be added or improved?

As a user I want to make it optional to show decimal number or not. 
I don't like numbers like this 2500.00

### Why do you need it?

-

**Comment by ivywallet** [comment] 2024-04-11 06:34
Thank you @Muhmad-hamdi for raising Issue #3120! 🚀
What's next? Read our **[Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md) 📚**.

_Tagging @ILIYANGERMANOV for review & approval 👀_

**Comment by ILIYANGERMANOV** [comment] 2024-04-11 07:32
Add a setting whether to show the ".00" decimal numbers or not. Decimal numbers should be should by default unless explicitly disabled. @Muhmad-hamdi please add more info - for example do you want to show "1233.XX"?

**Comment by Muhmad-hamdi** [comment] 2024-04-11 07:54
yes i want to add a setting whether to show the ".00" decimal numbers or not

**Comment by sandeepjak2007** [comment] 2024-04-14 08:47
It should reflect in all values right?

**Comment by Muhmad-hamdi** [comment] 2024-04-14 09:05
Yes

**Comment by ILIYANGERMANOV** [comment] 2024-04-14 09:11
@sandeepjak2007 make sure that the current behavior isn't broken in any way and that performance isn't affected. If that's not possible we ca skip implementing this setting. Also check the `IvyFeatures` class which should help for implementing the setting. There should also be a Features screen

**Comment by sandeepjak2007** [comment] 2024-04-14 09:14
Once will make changes and will check once then only try to push the changes

**Comment by shamim-emon** [comment] 2024-09-23 08:26
I'm on it

**Comment by ivywallet** [comment] 2024-09-23 08:29
Thank you for your interest @shamim-emon! 🎉
Issue #3120 is assigned to you. You can work on it! ✅

_If you don't want to work on it now, please un-assign yourself so other contributors can take it._

Also, make sure to read our [Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md).

**Comment by shamim-emon** [comment] 2024-09-23 08:36
@ILIYANGERMANOV 
I'm thinking, when the feature is enabled :
1. I'd make the changes in data layer.
2. I'd apply  flooring/Ceiling. eg: 2500.43 become 2500,  100.50 becomes 101.
Please let me know if that's alright or if you have any suggestion to add.

**Comment by ILIYANGERMANOV** [comment] 2024-09-23 08:46
> @ILIYANGERMANOV I'm thinking, when the feature is enabled :
> 
> 1. I'd make the changes in data layer.
> 2. I'd apply  flooring/Ceiling. eg: 2500.43 become 2500,  100.50 becomes 101.
>    Please let me know if that's alright or if you have any suggestion to add.

No, no. This change must be done in `:shared:ui`. We need a centralized `FormatMoneyUseCase` that does the proper Double -> String formatting based on user's settings

**Comment by ILIYANGERMANOV** [comment] 2024-09-23 08:48
The data layer must always return the true values. This is an UI feature that applies different formatting. Also centralizing all formatting in one usecase will be awesome. See how I did it for formatting date and time

**Comment by shamim-emon** [comment] 2024-09-23 08:50
> > @ILIYANGERMANOV I'm thinking, when the feature is enabled :
> > 
> > 1. I'd make the changes in data layer.
> > 2. I'd apply  flooring/Ceiling. eg: 2500.43 become 2500,  100.50 becomes 101.
> >    Please let me know if that's alright or if you have any suggestion to add.
> 
> No, no. This change must be done in `:shared:ui`. We need a centralized `FormatMoneyUseCase` that does the proper Double -> String formatting based on user's settings

Ok

**Comment by shamim-emon** [comment] 2024-09-25 11:39
@ILIYANGERMANOV want to share my current approach with this.
1. Creating a UseCase `FormatMoneyUseCase ` under` :shared:domain` (using domain package instead of ui as other useCases are under domain package).
2. FormatMoneyUseCase will have 1 method that will take double value and return Int(if decimal  place value is <.50 we will floor it otherwise ceil it eg: 2500.43 become 2500, 100.50 becomes 101)
3. Write UnitTest for 2 to confirm expected behaviour
4. Add a boolean ` IvyFeatures ` which by default will be false.
5. When concerned `IvyFeatures ` is set to true, in viewModels we will perform this conversion (Double to Int) for every double value using this useCase and otherwise will return default double value(Please note that I'm not planning to perform  the Int to String conversion within the usecase,  planning to do it in viewModels as we do for default value.

Let me know your, comment/suggestion and/or let me know if I got anything wrong.
Since this is going to be a wide-spread change, discussing the idea before hand.

**Comment by ILIYANGERMANOV** [comment] 2024-09-25 11:46
@shamim-emon 

> 1. Creating a UseCase FormatMoneyUseCase  under :shared:domain (using domain package instead of ui as other useCases are under domain package).

We have use-cases both in `:shared:ui` and `:shared:domain` depending on their responsibility. `FormatMoneyUseCase` is purely an UI layer thing and must be placed in `:shared:ui`.

> 2. FormatMoneyUseCase will have 1 method that will take double value and return Int(if decimal place value is <.50 we will floor it otherwise ceil it eg: 2500.43 become 2500, 100.50 becomes 101)

No no, formatting is an action of transforming domain data (Double, Instant etc) into String. It must have one method:
```
fun format(value: Value): String
```

> 5. When concerned IvyFeatures  is set to true, in viewModels we will perform this conversion (Double to Int) for every double value using this useCase and otherwise will return default double value(Please note that I'm not planning to perform the Int to String conversion within the usecase, planning to do it in viewModels as we do for default value.

Now that we have the `FormatMoneyUseCase` as a class in the DI graph, we can inject the `IvyFeatures` into it.
```kotlin
class FormatMoneyUseCase @Inject constructor(
  private val feature: Features
) {
//...
}
```

Once we have the `FormatMoneyUseCase` we can merge the PR only with its creation. Migration of existing screens to it will happen in follow-up PRs. Good idea for syncing the approach! 💯

**Comment by ILIYANGERMANOV** [comment] 2024-09-25 11:47
@shamim-emon and there is no rounding or Int calls anywhere, instead use `DecimalFormat`.

- `DecimalFormat("###,###") equivalent to rounding

Read the decimal format docs or even better ask ChatGPT for appropriate DecimalFormat for India. The decimal format will take care of the rounding

**Comment by shamim-emon** [comment] 2024-09-25 11:56
> @shamim-emon
> 
> > 1. Creating a UseCase FormatMoneyUseCase  under :shared:domain (using domain package instead of ui as other useCases are under domain package).
> 
> We have use-cases both in `:shared:ui` and `:shared:domain` depending on their responsibility. `FormatMoneyUseCase` is purely an UI layer thing and must be placed in `:shared:ui`.
> 
> > 2. FormatMoneyUseCase will have 1 method that will take double value and return Int(if decimal place value is <.50 we will floor it otherwise ceil it eg: 2500.43 become 2500, 100.50 becomes 101)
> 
> No no, formatting is an action of transforming domain data (Double, Instant etc) into String. It must have one method:
> 
> ```
> fun format(value: Value): String
> ```
> 
> > 5. When concerned IvyFeatures  is set to true, in viewModels we will perform this conversion (Double to Int) for every double value using this useCase and otherwise will return default double value(Please note that I'm not planning to perform the Int to String conversion within the usecase, planning to do it in viewModels as we do for default value.
> 
> Now that we have the `FormatMoneyUseCase` as a class in the DI graph, we can inject the `IvyFeatures` into it.
> 
> ```kotlin
> class FormatMoneyUseCase @Inject constructor(
>   private val feature: Features
> ) {
> //...
> }
> ```
> 
> Once we have the `FormatMoneyUseCase` we can merge the PR only with its creation. Migration of existing screens to it will happen in follow-up PRs. Good idea for syncing the approach! 💯

@ILIYANGERMANOV 
Awesome, just 2 more qeries:
1. `fun format(value: Value): String` the computation is insignificant, but would still prefer to make it suspending function & perform the computation in background thread. Is that alright? 
2.  I'm gonna create the useCase in marked package(just wanna double confirm)
![1](https://github.com/user-attachments/assets/90d97daa-ef3a-4efa-9328-eab58733cb44)

**Comment by ILIYANGERMANOV** [comment] 2024-09-25 12:04
@shamim-emon 

> 1. fun format(value: Value): String the computation is insignificant, but would still prefer to make it suspending function & perform the computation in background thread. Is that alright?

Yes, sounds good. Make it suspend operation.

> 2. I'm gonna create the useCase in marked package(just wanna double confirm)

Looks good, too!

**Comment by shamim-emon** [comment] 2024-09-29 09:51
@ILIYANGERMANOV I'm currently working on the task.
Facing issue with Tests. Seems like we can't use `mockk` in tests. Please have a look at the below sc.
Please note that I'm facing same error in any existing unit tests containing any mockked item.
![Capture](https://github.com/user-attachments/assets/470707e8-a74f-4a01-b11d-6094ab5e9fe8)

I haven't found any solution yet on this.
Is there any specific configuration to run Unit tests locally containing mockked items that I'm missing? or is it a bug?

**Comment by ILIYANGERMANOV** [comment] 2024-09-29 10:20
> @ILIYANGERMANOV I'm currently working on the task. Facing issue with Tests. Seems like we can't use `mockk` in tests. Please have a look at the below sc. Please note that I'm facing same error in any existing unit tests containing any mockked item. ![Capture](https://private-user-images.githubusercontent.com/60817041/371843475-470707e8-a74f-4a01-b11d-6094ab5e9fe8.PNG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc2MDU1MDQsIm5iZiI6MTcyNzYwNTIwNCwicGF0aCI6Ii82MDgxNzA0MS8zNzE4NDM0NzUtNDcwNzA3ZTgtYTc0Zi00YTAxLWIxMWQtNjA5NGFiNWU5ZmU4LlBORz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI5VDEwMjAwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZhMDVkYTBjN2NkMDBkMDc0ZGViZWZmMjE1ZDhlMmU5MjAwMDk0ZWY5NWY3ZTY2MDNjYTM5YTc4ZWY0YzM2MTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.p1HxphiRER_OpWxSGOdZlqt3bCJz0qk4wfBVIml0sDE)
> 
> I haven't found any solution yet on this. Is there any specific configuration to run Unit tests locally containing mockked items that I'm missing? or is it a bug?

@shamim-emon raise a PR, you've setup something incorrectly

**Comment by shamim-emon** [comment] 2024-09-29 10:51
@ILIYANGERMANOV I have tried running entire test file and same issue.
here is the draft PR https://github.com/Ivy-Apps/ivy-wallet/pull/3568

**Closed** 2024-09-30 17:00 UTC
Labels: user request, approved, keep, P2
