### ISSUE TITLE
Automatic/Planned Transfers

### ISSUE THREAD

**Issue by ivywallet** [Ivy-Apps/ivy-wallet#1216] opened 2022-08-16 00:41 UTC
I have scheduled account transfers; would be nice to easily represent this without making a category and creating an expense + income planned payment

**Comment by Aditya137x** [comment] 2022-08-25 13:39
Duplicate of https://github.com/Ivy-Apps/ivy-wallet/issues/173

**Closed by Aditya137x** 2022-08-25 13:39 UTC
