### ISSUE TITLE
[FEATURES] ...

### ISSUE THREAD

**Issue by Zakariyya-47** [Ivy-Apps/ivy-wallet#1333] opened 2022-09-26 21:33 UTC
### Please confirm the following

- [X] I checked [the current issues](https://github.com/ILIYANGERMANOV/ivy-wallet/issues) for duplicate problems

### What do you want to be added or improved?

As a user I want to have an ios app

### Why do you need it?

- I just bought an ios and sadly i cant use the app and must find something similar which soo far isnt going well

### How do you imagine it?

not sure how the implementation would work

**Comment by code-a1** [comment] 2022-10-04 19:48
Duplicate of #81

**Closed by code-a1** 2022-10-04 19:48 UTC
Labels: user request
