### ISSUE TITLE
Widgets showing so many decimals 

### ISSUE THREAD

**Issue by Karnamaharaja** [Ivy-Apps/ivy-wallet#2904] opened 2024-01-30 05:46 UTC
### Please confirm the following

- [X] I checked [the current issues](https://github.com/Ivy-Apps/ivy-wallet/issues) for duplicate problems

### Describe the bug

When the total amount is above 1k rupees its fine like always but when the total amount is below 1k rupees along with some decimals (like 367.34) it adds up so many zeros 

_No response_

### Screenshots

![Screenshot_2024-01-25-12-29-26-71_b783bf344239542886fee7b48fa4b892](https://github.com/Ivy-Apps/ivy-wallet/assets/85229078/bf2f2e73-5ad7-487a-94bd-1cbfd77a1338)

### Smartphone

realme 9 5G Speed Edition

**Comment by ivywallet** [comment] 2024-01-30 05:47
Thank you @Karnamaharaja for raising Issue #2904! 🚀
What's next? Read our **[Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md) 📚**.

_Tagging @ILIYANGERMANOV for review & approval 👀_

**Comment by sandeepjak2007** [comment] 2024-02-08 18:03
I'm on it

**Comment by sandeepjak2007** [comment] 2024-02-08 18:06
> I'm on it

Have made changes but have to test once. So Can you suggest to me the steps to run the wallet?

**Comment by sandeepjak2007** [comment] 2024-02-08 18:10
> ⚠️ Hey @sandeepjak2007, this issue is already taken by @sandeepjak2007. **Do not start working on it!** Please, [pick another one](https://github.com/Ivy-Apps/ivy-wallet/issues).
> 
> Also, make sure to read our [Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md).

Hey Bot, Two are the same 😄😄😄

**Comment by MAlini-Krishnan3** [comment] 2024-02-27 17:36
@ILIYANGERMANOV @Karnamaharaja is this still reproducible? Or has this been fixed?
I wasn't able to reproduce this issue on the latest pull

**Comment by ILIYANGERMANOV** [comment] 2024-02-27 17:41
> @ILIYANGERMANOV @Karnamaharaja is this still reproducible? Or has this been fixed? I wasn't able to reproduce this issue on the latest pull

It isn't, you were just lucky the Double to round without issues

**Comment by DripYeager** [comment] 2024-03-15 10:32
I wanted to work on it but i was also not able to reproduce it. Is it fixed?

**Comment by ILIYANGERMANOV** [comment] 2024-03-15 10:35
It's not fixed just harder to repro - formatting in the widget is still missing

**Comment by ILIYANGERMANOV** [comment] 2024-03-15 10:36
double.toString() = bug
fix: DecimalFormat

**Comment by DripYeager** [comment] 2024-03-16 19:20
I'm on it

**Comment by ivywallet** [comment] 2024-03-16 19:22
Thank you for your interest @DripYeager! 🎉
Issue #2904 is assigned to you. You can work on it! ✅

_If you don't want to work on it now, please un-assign yourself so other contributors can take it._

Also, make sure to read our [Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md).

**Comment by DripYeager** [comment] 2024-03-16 19:47
I have made the change, go through it once.

**Comment by idkwebdev** [comment] 2024-05-31 02:27
I'd like to point out that I've also encountered this issue. From the looks of things, I guess this has been fixed an we're just waiting for a build to be uploaded to the Play Store.
![Screenshot_20240530-221049_One UI Home](https://github.com/Ivy-Apps/ivy-wallet/assets/70406184/33a07274-5fd2-4f3f-b591-3e9c3fa3d51f)

**Comment by suyash01** [comment] 2024-07-06 06:54
@ILIYANGERMANOV this can be closed as fix has already been merged.

**Closed** 2024-07-06 11:03 UTC
Labels: bug, good first issue, help wanted, approved, keep, P1, java
