### ISSUE TITLE
[FEATURE] SAVING PICTURE FOR PROOF OF EXPENSES OR INCOME

### ISSUE THREAD

**Issue by yahyanor** [Ivy-Apps/ivy-wallet#3354] opened 2024-07-20 14:32 UTC
### Please confirm the following:

- [X] I've checked [the current issues](https://github.com/Ivy-Apps/ivy-wallet/issues) for duplicate issues.
- [X] I've requested a single (only one) feature/change in this issue. It complies with the One Request Per GitHub Issue (ORPGI) rule.
- [X] My issue is well-defined and describes how it should be implemented from UI/UX perspective.

### What do you want to be added or improved?

As a user I want to able to save or taking picture proof of payment or income, that way we can track and able to keep

### Why do you need it?

- it's keep me tracked and the proof can be used since paper proof can be lost

### How do you imagine it?

When you adding the nominal and tags etc, down below please add a tab that can be click to choose file or taking pic, and adding it to widget with one click can be directed to camera in the app for fast add.

Thank you, and sorry if it's a bit much.

**Comment by ivywallet** [comment] 2024-07-20 14:34
Thank you @yahyanor for raising Issue #3354! 🚀
What's next? Read our **[Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md) 📚**.

_Tagging @ILIYANGERMANOV for review & approval 👀_

**Comment by ILIYANGERMANOV** [comment] 2024-07-20 21:05
Duplicate of #3316

**Closed by ILIYANGERMANOV** 2024-07-20 21:05 UTC
Labels: user request
