### ISSUE TITLE
Planned Payment End Date

### ISSUE THREAD

**Issue by ivywallet** [Ivy-Apps/ivy-wallet#838] opened 2022-05-03 16:13 UTC
Ability to set an end date for a planned payment. I.e. certain payments may only be for a couple of months

**Comment by Pkcarreno** [comment] 2022-06-03 19:22
Duplicate of https://github.com/ILIYANGERMANOV/ivy-wallet/issues/143

**Closed** 2022-08-25 08:46 UTC
