### ISSUE TITLE
End Date For Planned Payments

### ISSUE THREAD

**Issue by ivywallet** [Ivy-Apps/ivy-wallet#653] opened 2022-03-30 06:11 UTC
End Date For Planned Payments

**Comment by Pkcarreno** [comment] 2022-06-03 19:22
Duplicate of https://github.com/ILIYANGERMANOV/ivy-wallet/issues/143

**Comment by Aditya137x** [comment] 2022-08-24 10:33
Duplicate of https://github.com/Ivy-Apps/ivy-wallet/issues/143

**Closed by Aditya137x** 2022-08-24 10:33 UTC
