### ISSUE TITLE
Subcategories 

### ISSUE THREAD

**Issue by ivywallet** [Ivy-Apps/ivy-wallet#1594] opened 2022-12-12 12:03 UTC
It will be a lot easier if I can have subcategories for general categories. Makes tracking more filtered. Thanks

**Comment by theRealPadster** [comment] 2023-01-23 03:34
Dupe of https://github.com/Ivy-Apps/ivy-wallet/issues/1747

**Closed** 2023-08-31 22:06 UTC
