### ISSUE TITLE
[BUG] Expense not updating on the main screen

### ISSUE THREAD

**Issue by diasmashikov** [Ivy-Apps/ivy-wallet#3002] opened 2024-02-29 21:10 UTC
### Please confirm the following

- [X] I checked [the current issues](https://github.com/Ivy-Apps/ivy-wallet/issues) for duplicate problems

### Describe the bug

If I click to add a new expense, then save it, changes are not shown on the UI even if I turn off and turn on the app. Testing was done on the production app from Google Playstore

### To Reproduce

1. Add expense
2. Check the home tab
3. Leave the app, you can shut it down completely
4. Enter the app, expenses are the same

### Expected behavior

No change in expense

### Screenshots

Attaching the video 

https://github.com/Ivy-Apps/ivy-wallet/assets/50723693/064c4c33-1aad-487e-9a84-3ffc86420970

### Smartphone

Samsung S9

**Comment by ivywallet** [comment] 2024-02-29 21:12
Thank you @diasmashikov for raising Issue #3002! 🚀
What's next? Read our **[Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md) 📚**.

_Tagging @ILIYANGERMANOV for review & approval 👀_

**Comment by Saifuddin53** [comment] 2024-03-03 07:19
@ILIYANGERMANOV & @diasmashikov I think this issue arises only when we change the currency from one to another from setting otherwise it works perfectly
So when we change it to another currency the expense tracker dialog takes input currency in the form of the prior currency but in the home screen expense tracker it shows for the current currency

**Comment by Natzee** [comment] 2024-03-04 13:44
@Saifuddin53 Can you share screen recording when you change currency

**Comment by Saifuddin53** [comment] 2024-03-04 16:42
Uploading Screen_Recording_20240304_220729.mp4…

**Comment by Saifuddin53** [comment] 2024-03-04 16:50
https://github.com/Ivy-Apps/ivy-wallet/assets/112172255/2189cf8a-a465-41de-9dd0-6b5807558bbc

**Comment by Natzee** [comment] 2024-03-04 17:08
@Saifuddin53 Thanks for sharing screen recordings. I have followed your step but not able to reproduce, so sharing my screen recordings here and guide me if I done wrong.

https://github.com/Ivy-Apps/ivy-wallet/assets/68009703/edd27e7a-c247-4252-9af2-62def9c1701a

**Comment by wannabetolkien** [comment] 2024-03-05 06:11
Hi @Natzee , I followed the same steps and was able to reproduce  the issue. After changing the currency all the expenses that were logged in with previous currency were lost from the expense tab on the top. No new transactions are getting added as well. They are being logged as expense for Today in the bottom but no updation at the top.

**Comment by Vishwa-Raghavendra** [comment] 2024-03-24 12:00
I'm on it

**Comment by ivywallet** [comment] 2024-03-24 12:02
Thank you for your interest @Vishwa-Raghavendra! 🎉
Issue #3002 is assigned to you. You can work on it! ✅

_If you don't want to work on it now, please un-assign yourself so other contributors can take it._

Also, make sure to read our [Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md).

**Comment by Vishwa-Raghavendra** [comment] 2024-03-24 12:06
https://github.com/Ivy-Apps/ivy-wallet/pull/3036
This PR fixes this Bug 
It can be closed now

**Closed** 2024-03-24 12:21 UTC
Labels: bug, good first issue, help wanted, approved, P0
