### ISSUE TITLE
Specify Second Currency Instead Of Rate In Account Transfer

### ISSUE THREAD

**Issue by ivywallet** [Ivy-Apps/ivy-wallet#1209] opened 2022-08-13 08:09 UTC
Much easier than calculating the rate, especially since calculator is not precise enough

**Comment by Aditya137x** [comment] 2022-08-25 13:37
Duplicate of https://github.com/Ivy-Apps/ivy-wallet/issues/1069

**Closed by Aditya137x** 2022-08-25 13:37 UTC
