### ISSUE TITLE
Credit Card Expense 

### ISSUE THREAD

**Issue by ivywallet** [Ivy-Apps/ivy-wallet#754] opened 2022-04-20 02:03 UTC
Implement a way to track the usage of credit cards and then align it with the account used to pay the monthlies for the credit card

**Comment by Aditya137x** [comment] 2022-08-24 10:59
Duplicate of https://github.com/Ivy-Apps/ivy-wallet/issues/11

**Closed by Aditya137x** 2022-08-24 10:59 UTC
