### ISSUE TITLE
Planned Recurring Amount  Start And End Datr

### ISSUE THREAD

**Issue by ivywallet** [Ivy-Apps/ivy-wallet#960] opened 2022-05-27 07:09 UTC
Example: I have 40,000 to be paid in 4 months. 
Start Date : June
End Date : September

**Comment by Pkcarreno** [comment] 2022-06-03 19:21
Duplicate of https://github.com/ILIYANGERMANOV/ivy-wallet/issues/143

**Closed** 2022-08-25 08:46 UTC
