### ISSUE TITLE
Multiple Categories 

### ISSUE THREAD

**Issue by ivywallet** [Ivy-Apps/ivy-wallet#1124] opened 2022-07-14 07:58 UTC
Need to categorize my expenses in different ways. For example meals in an off day and meals on vacation, I would like to be able to categorize both as meals, but have a secondary tag.

**Comment by Aditya137x** [comment] 2022-08-25 08:25
Duplicate of https://github.com/Ivy-Apps/ivy-wallet/issues/7

**Closed by Aditya137x** 2022-08-25 08:25 UTC
