### ISSUE TITLE
I would like to have subcategories. These should be delectable when recording a payment.  Nice to have would be the ability to set budgets per subcategory

### ISSUE THREAD

**Issue by ivywallet** [Ivy-Apps/ivy-wallet#1555] opened 2022-11-29 18:44 UTC

**Comment by theRealPadster** [comment] 2023-01-23 03:34
Dupe of https://github.com/Ivy-Apps/ivy-wallet/issues/1747

**Closed** 2023-08-31 22:07 UTC
