### ISSUE TITLE
A Savings Feature, 

### ISSUE THREAD

**Issue by ivywallet** [Ivy-Apps/ivy-wallet#958] opened 2022-05-26 21:33 UTC
A goal for a certain amount to be the difference between income and expense.
Eg-
Savings goal- 100$
Income - 1000$
Expense -990$

Goal- 90% done ( similar to the progress bar in budget)

**Comment by Aditya137x** [comment] 2022-08-25 13:21
Duplicate of https://github.com/Ivy-Apps/ivy-wallet/issues/111

**Closed by Aditya137x** 2022-08-25 13:21 UTC
