### ISSUE TITLE
Subcategories

### ISSUE THREAD

**Issue by ivywallet** [Ivy-Apps/ivy-wallet#1544] opened 2022-11-26 08:45 UTC
I would like to have subcategories, so for example the general category could be "food" and the subcategories "restaurant" and "supermarket". They would be accounted for in the main category but there would also be a control of spending by subcategory.

**Comment by theRealPadster** [comment] 2023-01-23 03:35
Dupe of https://github.com/Ivy-Apps/ivy-wallet/issues/1747

**Closed** 2023-08-31 22:07 UTC
