### ISSUE TITLE
Save a pic below description 

### ISSUE THREAD

**Issue by ivywallet** [Ivy-Apps/ivy-wallet#1694] opened 2023-01-07 19:15 UTC
Save the receipt as an image blow the description

**Comment by MaximilianMauroner** [comment] 2023-01-07 19:20
I was thinking of doing it similarly to the way Revolut does it. [something like this](https://www.nsbanking.com/wp-content/uploads/sites/7/2019/08/Press-image-%E2%80%94-Desktop.png)

**Comment by ILIYANGERMANOV** [comment] 2023-01-07 20:05
@MaximilianMauroner this feature is a good one! It's planned but we need to implement the Google Drive sync + data backup first.

**Comment by MaximilianMauroner** [comment] 2023-01-09 14:06
I'll just add this since I saw it was added for the other similar issues as well

Duplicate of https://github.com/Ivy-Apps/ivy-wallet/issues/6

**Closed** 2023-08-31 22:05 UTC
