### ISSUE TITLE
A Way To Track The Money I Put In Investments And Deposits. Currently, I'm Adding Them Under Expenses.

### ISSUE THREAD

**Issue by ivywallet** [Ivy-Apps/ivy-wallet#1001] opened 2022-06-04 08:48 UTC

**Comment by Aditya137x** [comment] 2022-08-25 08:53
You can created different account and transfer funds between them. Duplicate of https://github.com/Ivy-Apps/ivy-wallet/issues/278

**Closed by Aditya137x** 2022-08-25 08:53 UTC
