### ISSUE TITLE
Ability To Add Sub Categories, Exclude Categories From Total Balance, and Set Currency For Each Category.

### ISSUE THREAD

**Issue by ivywallet** [Ivy-Apps/ivy-wallet#607] opened 2022-03-15 07:46 UTC

**Comment by MohitMandalia** [comment] 2022-03-28 07:38
probably same as #7 but has a slight different request.

**Comment by Aditya137x** [comment] 2022-08-25 07:51
Duplicate of https://github.com/Ivy-Apps/ivy-wallet/issues/7

**Closed by Aditya137x** 2022-08-25 07:51 UTC
