### ISSUE TITLE
Credit Card Option. I'd Like To See How Much Credit I Have And The Balance Against It. Instead At Least Have Negative Balance Option So I Can Track Negative Balance Or Dues

### ISSUE THREAD

**Issue by ivywallet** [Ivy-Apps/ivy-wallet#1228] opened 2022-08-20 12:56 UTC

**Comment by Aditya137x** [comment] 2022-08-24 11:00
Duplicate of https://github.com/Ivy-Apps/ivy-wallet/issues/11

**Closed by Aditya137x** 2022-08-24 11:00 UTC
