### ISSUE TITLE
[BUG] The adjust value was not right

### ISSUE THREAD

**Issue by hkjansonchan** [Ivy-Apps/ivy-wallet#3150] opened 2024-04-19 09:30 UTC
### Please confirm the following

- [X] I checked [the current issues](https://github.com/Ivy-Apps/ivy-wallet/issues) for duplicate problems

### Describe the bug

I would like to adjust the value but it doesn't match what I input 

### To Reproduce

1. 

### Screenshots

https://github.com/Ivy-Apps/ivy-wallet/assets/91411747/6eec8abc-5319-4b2a-91b6-6939de06bf95

### App version

4.6.3 (163) from Play Sto5

### Smartphone

Galaxy A54

**Comment by ILIYANGERMANOV** [comment] 2024-04-19 13:17
Duplicate of #3119

**Closed by ILIYANGERMANOV** 2024-04-19 13:17 UTC
Labels: bug
