### ISSUE TITLE
[BUG] Loan categories not working properly

### ISSUE THREAD

**Issue by Okazakee** [Ivy-Apps/ivy-wallet#3047] opened 2024-03-27 19:14 UTC
### Please confirm the following

- [X] I checked [the current issues](https://github.com/Ivy-Apps/ivy-wallet/issues) for duplicate problems

### Describe the bug

The app creates a new category for each loan added.

### To Reproduce

1. Upon adding a new loan, a new category is created.

### Expected behavior

No categories are added multiple times on loan addition.

### Screenshots

![4909228296449928238_121](https://github.com/Ivy-Apps/ivy-wallet/assets/17621558/a08239e9-3900-43ef-8bf5-2900ef4f0580)

### Smartphone

Any

**Comment by isaacnguyen0809** [comment] 2024-04-01 07:40
I'm on it

**Comment by ivywallet** [comment] 2024-04-01 07:43
Thank you for your interest @isaacnguyen0809! 🎉
Issue #3047 is assigned to you. You can work on it! ✅

_If you don't want to work on it now, please un-assign yourself so other contributors can take it._

Also, make sure to read our [Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md).

**Comment by isaacnguyen0809** [comment] 2024-04-01 09:05
Hi @Okazakee, can you provide me a video of how you do it, I can't reproduce it at the moment. It will be very helpful for me to find out the root cause.

**Closed** 2024-04-07 12:13 UTC
Labels: bug, good first issue, help wanted, approved, P1
