### ISSUE TITLE
Ability To Add Images

### ISSUE THREAD

**Issue by ivywallet** [Ivy-Apps/ivy-wallet#1093] opened 2022-07-05 06:24 UTC

**Comment by Pkcarreno** [comment] 2022-07-29 13:57
Same as https://github.com/ILIYANGERMANOV/ivy-wallet/issues/939

**Comment by code-a1** [comment] 2022-08-22 14:30
#1241 Duplicate

**Comment by Aditya137x** [comment] 2022-08-25 13:45
Duplicate of https://github.com/Ivy-Apps/ivy-wallet/issues/6

**Closed by Aditya137x** 2022-08-25 13:45 UTC
Labels: duplicate, feature, user request
