### ISSUE TITLE
[BUG] Transaction being added to the wrong date after changing time (timezone issue)

### ISSUE THREAD

**Issue by rekcrimson** [Ivy-Apps/ivy-wallet#3118] opened 2024-04-10 21:16 UTC
### Please confirm the following

- [X] I checked [the current issues](https://github.com/Ivy-Apps/ivy-wallet/issues) for duplicate problems

### Describe the bug

Al querer configurar la hora en los registros de gastos e ingresos, si selecciono una hora después de las 6:00pm lo marca automáticamente como si la transacción se hubiera hecho el día siguiente. 

### To Reproduce

1. Agregar gasto.
2. Seleccionar cuenta.
3. Ingresar monto.
4. Clic en botón "Ingresar".
5. Seleccionar categoría.
6. Ingresar título del gasto.
7. Configurar el día en el calendario.
8. Configurar hora. 
9. Si la hora es después de las 18:00 aparece el bug, ya que la transacción se convierte y queda en la fecha del día siguiente y no en el seleccionado.

### Expected behavior

Que la hora y fecha queden como debe ser de acuerdo a lo configurado. Este bug no ocurría en la versión anterior. 

### Screenshots

![Screenshot_2024-04-10-16-14-19-154_com ivy wallet](https://github.com/Ivy-Apps/ivy-wallet/assets/166661013/93ee91a5-e357-48a8-8488-e60ff53d428b)
![Screenshot_2024-04-10-16-14-24-172_com ivy wallet](https://github.com/Ivy-Apps/ivy-wallet/assets/166661013/0956d1b4-807a-40a7-839b-95e293b565e3)

### App version

4.6.2 from Google Play Store for Android

### Smartphone

Xiaomi Redmi Note 10S

**Comment by ivywallet** [comment] 2024-04-10 21:18
Thank you @rekcrimson for raising Issue #3118! 🚀
What's next? Read our **[Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md) 📚**.

_Tagging @ILIYANGERMANOV for review & approval 👀_

**Comment by ILIYANGERMANOV** [comment] 2024-04-10 21:25
Hello @rekcrimson thanks for reporting! Would you translate it to English? I don't understand Spanish and also most contributors won't be able to

**Comment by faerbersteve** [comment] 2024-04-11 01:04
I can reproduce the issue as well.
In short try the following to reproduce the issue: 
Add an expense, set any value and jump to the datetime control.
It shows 10 Apr but after changing only the time e.g. to 6pm the date jumps to 11 Apr.
The expense is then saved with date 11 Apr and not 10 Apr as intended.
@rekcrimson screenshots show the issue

Btw, is there any chance to get 24h clock back instead of 12 hour clock?
Had the 24h clock until the new update

**Comment by ILIYANGERMANOV** [comment] 2024-04-11 07:28
Thanks for translating @faerbersteve! Can you create an separate issue for the 12/24 clock to be shown depending on user's Android system settings?

**Comment by ILIYANGERMANOV** [comment] 2024-04-11 07:50
It's timezones issues. We don't treat transactions time properly.

**Comment by ILIYANGERMANOV** [comment] 2024-04-11 07:51
I'm on it

**Comment by ivywallet** [comment] 2024-04-11 07:52
Thank you for your interest @ILIYANGERMANOV! 🎉
Issue #3118 is assigned to you. You can work on it! ✅

_If you don't want to work on it now, please un-assign yourself so other contributors can take it._

Also, make sure to read our [Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md).

**Comment by Vivekban** [comment] 2024-05-01 11:16
@ILIYANGERMANOV I want to work on this, Can you give me an idea how we want to solve this problem? How do you want to save time etc, what will be the impact of change on other functionalities?

**Comment by ILIYANGERMANOV** [comment] 2024-05-01 11:24
Hey @Vivekban yes, here's how to fix it:
1. Change TransactionsEntity and DB time to `Instant`
2. Convert Instant to formatted local datetime only in the UI layer
3. Add a `FormatTimeUseCase` in ":shared:ui:core" that turns an Instant (UTC) to formatted String in local time
4. Update VM's to use the new use-case

**Logic:**
- Everything in the DB and domain logic is in UTC (Instant) => no time zones
- When all computations are done the UI layer converts the UTC time into user's local
- Note: You might also need to update the Date/Time pickers

Does that helps?

**Comment by Vivekban** [comment] 2024-05-01 11:39
I'm on it

**Comment by ivywallet** [comment] 2024-05-01 11:41
Thank you for your interest @Vivekban! 🎉
Issue #3118 is assigned to you. You can work on it! ✅

_If you don't want to work on it now, please un-assign yourself so other contributors can take it._

Also, make sure to read our [Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md).

**Comment by ILIYANGERMANOV** [comment] 2024-06-02 09:35
Should be fixed in https://github.com/Ivy-Apps/ivy-wallet/pull/3224

**Closed by ILIYANGERMANOV** 2024-06-02 09:35 UTC
Labels: bug, help wanted, approved, P0
